version: '3'

services:
  web:
    image: expenses:latest  # Replace 'your-flask-app-image' with your actual image name
    ports:
      - "8000:5000"
    depends_on:
      - db
      - pg-admin
    environment:
      - DATABASE_URL=postgresql://postgres:rain1234@172.23.0.2:5432/expenses

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: expenses
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rain1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

volumes:
  postgres_data:
