"""datum toevoegen

Revision ID: 72e25a9be020
Revises: 723df70b931c
Create Date: 2024-03-01 13:37:32.432348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e25a9be020'
down_revision = '723df70b931c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.create_index(batch_op.f('ix_expenses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_name'))
        batch_op.drop_index(batch_op.f('ix_expenses_date'))
        batch_op.drop_index(batch_op.f('ix_expenses_category'))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
